In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3,4,5]) # Creating numpy array

In [3]:
array_1

array([1, 2, 3, 4, 5])

Creating multidimensional array

In [4]:
array_2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

In [5]:
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array_3 = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
print(array_3)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
array_3.ndim # shows dimensions of array

1

In [9]:
array_3.shape # shape of array (rows,columns)

(10,)

In [11]:
array_4 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

In [12]:
array_4.shape

(2, 3)

In [10]:
array_3.dtype # shows datatype of elements of array

dtype('int32')

In [14]:
rows = 3
columns = 2
array_4.reshape(rows,columns)

array([[1, 2],
       [3, 4],
       [5, 6]])

arange

In [15]:
#this is function creates the number between a range
#you have to provide start point,end point,step
start_point = 0
end_point = 10
step = 1
array_5 = np.arange(start_point,end_point,step)

In [16]:
print(array_5)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
end_point = 21
array_6 = np.arange(end_point)
# this will make array starting from 0 to 20

In [18]:
print(array_6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
rows = 7
columns = 3
array_6.reshape(rows,columns)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [21]:
start_point = 1
end_Point = 21
step = 2
rows = 5
columns = 2
array_7 = np.arange(start_point,end_point,step).reshape(rows,columns)

In [22]:
print(array_7)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [24]:
np.arange(0,2,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [31]:
rows = 3
columns = 2
array_8 = np.empty([rows,columns],dtype=np.complex64) 
# creates empty array with any values of given datatype

In [32]:
print(array_8)

[[8.9683102e-44+0.0000000e+00j 0.0000000e+00+0.0000000e+00j]
 [5.2897435e+22+5.2431659e-08j 5.3406612e-08+2.5965680e+20j]
 [5.2941871e-08+3.3092588e+21j 1.6426634e-07+4.3683121e-05j]]


In [36]:
rows = 3
columns = 3
array_9 = np.zeros([rows,columns],dtype=np.float16)

In [37]:
print(array_9)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
rows = 3
columns = 4
array_10 = np.ones([rows,columns])

In [39]:
print(array_10)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
